name: direct-build-release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Set VERSION from git tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o fp2lm.exe ./cmd/fp2lm

      - name: Build for macOS (Intel)
        run: |
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o fp2lm_darwin_amd64 ./cmd/fp2lm

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o fp2lm_linux_amd64 ./cmd/fp2lm

      - name: Create ZIP for Windows
        run: |
          zip -j fp2lm_windows_amd64.zip fp2lm.exe README.md LICENSE

      - name: Create TAR for macOS
        run: |
          tar czf fp2lm_darwin_amd64.tar.gz fp2lm_darwin_amd64 README.md LICENSE

      - name: Create TAR for Linux
        run: |
          tar czf fp2lm_linux_amd64.tar.gz fp2lm_linux_amd64 README.md LICENSE

      - name: List files (debug)
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Files to be uploaded:"
          ls -la fp2lm_windows_amd64.zip fp2lm_darwin_amd64.tar.gz fp2lm_linux_amd64.tar.gz || echo "Some files missing!"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          draft: true
          files: |
            fp2lm_windows_amd64.zip
            fp2lm_darwin_amd64.tar.gz
            fp2lm_linux_amd64.tar.gz 