name: build-and-release

on:
  # build binaries on demand (`v1.2.3`, `v0.9.0-beta1`, …)
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write                # to create the Release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GoReleaser to build properly

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          
      - name: Initialize dependencies
        run: |
          go mod tidy

      - name: Run GoReleaser with Debug
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --debug
          
      - name: List dist directory contents (debug)
        run: |
          echo "Dist directory contents:"
          ls -la dist/ || echo "dist directory not found!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Below are needed if you want to sign your releases
          # GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
          # PASSPHRASE: ${{ secrets.PASSPHRASE }} 